### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by CiaranOMara** [JuliaWeb/LibCURLBuilder#13]
Would it be possible to include FreeBSD in the build?

I want to use the FTPClient.jl package on a FreeBSD system, unless there is an alternative more suitable package?

**Comment by omus** [comment]
Currently FreeBSD support isn't available in this package due to this issue: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/390

Older versions of LibCURLBuilder did support FreeBSD but it was dropped in this PR: https://github.com/JuliaWeb/LibCURLBuilder/pull/12

**Comment by omus** [comment]
It appears that ZlibBuilder v1.0.4 may address the problem: https://github.com/bicycle1885/ZlibBuilder/releases/tag/v1.0.4

**Comment by omus** [comment]
FTPClient.jl should work on FreeBSD with LibCURL.jl 0.5.1. I've made a small update to FTPClient.jl to ensure the correct version of LibCURL is installed: https://github.com/invenia/FTPClient.jl/pull/86

**Comment by CiaranOMara** [comment]
@omus, that's fantastic. Thank you very much.
