### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by geokollias** [JuliaWeb/LibCURLBuilder#18]
Currently, the way libcurl is built doesn't support HTTP/2. Is that on purpose? If not, it'd be nice to add, especially given that HTTP.jl doesn't support HTTP/2 yet. I think HTTP/2 would require at least `nghttp2` as dependency. I'd be glad to help with that btw.

**Comment by omus** [comment]
You may want to take a look at https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibCURL/build_tarballs.jl and https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl as LibCURL.jl should be [switching to that binary builder](https://github.com/JuliaWeb/LibCURL.jl/pull/75).

**Comment by geokollias** [comment]
Thanks @omus. Added `nghttp2` to Yggdrasil [here](https://github.com/JuliaPackaging/Yggdrasil/tree/master/N/nghttp2) yesterday and have opened a PR [here](https://github.com/JuliaPackaging/Yggdrasil/pull/957) for HTTP/2 support. I think it's critical given that there is no other well-maintained Julia library supporting HTTP/2.
